### ISSUE TITLE
As a logged in user on the demo, I can't create new passwords

### ISSUE THREAD

**Issue by lln-ijinus** [passbolt/passbolt#3] opened 2016-04-18 08:20 UTC
First time i tried to create a password, during entering the password, Firefox crashed.
After a restart, the password field is not visible.
![clipboard01](https://cloud.githubusercontent.com/assets/14195094/14597770/26cd55f2-054f-11e6-8937-3bb8af335334.png)

**Comment by lln-ijinus** [comment] 2016-04-18 08:34
Trying to logout the login, I'm not able to login anymore, I need to register again 
Message "Firefox plugin is installed but not configured. Please register!" on the login page.
Also using again the registering link in the email show me the "please register" page.
And when trying to register again with the same email is not allowed.

**Comment by stripthis** [comment] 2016-04-18 08:45
Hello, can you give us your operating system and firefox version?

**Comment by lln-ijinus** [comment] 2016-04-18 08:46
Firefox 45.0.2 on Windows 7 32 bit


Laurent Lauden Ijinus

**Comment by stripthis** [comment] 2016-04-18 08:47
Thanks, we'll see if we can reproduce the error!

**Comment by cedricalfonsi** [comment] 2016-04-23 11:49
Hello  lln-ijinus,

We're not able to reproduce the bug one the same environment.
Can you give us a stack trace from the browser console.
https://developer.mozilla.org/en-US/docs/Tools/Browser_Console

Thanks

**Comment by stripthis** [comment] 2016-04-25 15:09
We got another report of the same issue by email with FireFox browser version 45.0.2 on OS X 10.11.4

**Comment by stripthis** [comment] 2016-04-28 10:43
Shruti could reproduce this. It seems to happen when the browser extension is updated by Firefox while using passbolt. Most likely the PassboltAppPagemod doesn't like this. Ref. PASSBOLT-1494

**Comment by cedricalfonsi** [comment] 2016-06-06 09:05
I'm closing this issue as I can't reproduce it on the same environment (W7, FF45.02).
Since the version 1.0.8 (15 april), the code relative to the plugin workers has been improved.

@lln-ijinus do you still experience this issue with the latest version of the plugin ?
If yes, can you give us more details, we'll reopen this issue.

**Closed by cedricalfonsi** 2016-06-06 09:05 UTC
Labels: bug
