### ISSUE TITLE
Error "The server was unable to respect the authentication protocol." GPGAuth headers are transformed to lower case by NGINX

### ISSUE THREAD

**Issue by infectormp** [passbolt/passbolt#16] opened 2016-08-17 09:11 UTC
After i finish install and try login to passbolt i get message 

> The server was unable to respect the authentication protocol.

and i don't understand what is wrong.

**Comment by stripthis** [comment] 2016-08-17 10:32
Hi @infectormp,

This means that the HTTP headers returned by the webserver do not follow the GPGAuth protocol.
Maybe your server configuration supresses headers such as X-GPGAuth-* ?

![screen shot 2016-08-17 at 12 31 32](https://cloud.githubusercontent.com/assets/77410/17733382/929e62ae-6476-11e6-9435-ef138dc5eee3.png)

Let us know how it goes, if you're stuck with nginx we will have a look!
Thanks again,

**Comment by infectormp** [comment] 2016-08-17 10:37
here is my headers

![image](https://cloud.githubusercontent.com/assets/9958813/17733501/a08c0912-647f-11e6-9e37-88b210dd002b.png)

**Comment by stripthis** [comment] 2016-08-17 10:41
There seems to be a difference in the caps, I suspect that might be the cause. I had the same issue client side with Nodejs, we'll have a look and release a fix in an upcoming release. Sorry for the bumpy ride!

**Comment by infectormp** [comment] 2016-08-17 10:51
thanks you, i will wait a fix.

**Comment by stripthis** [comment] 2016-10-11 13:44
@infectormp i've tested on nginx today and didn't get the header in lower case. We can also rule out also the OS as we have report of people succesfully running passbolt on Gentoo. 
It can't be php7 either since @vesln on #24 is having the same issue but on demo environment itself. Maybe it could come from the client operating system? Or a device on your network like a router?

We've worked on a fix for this anyway (1.1.2 coming up this week!), but at this stage I'm curious what is the root cause of these changes in capitalization. Let us know if you find something.

**Comment by infectormp** [comment] 2016-10-11 14:25
@stripthis possible reason in http/2

https://http2.github.io/http2-spec/

> 8.1.2 HTTP Header Fields
Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion. However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2. A request or response containing uppercase header field names MUST be treated as malformed

**Comment by stripthis** [comment] 2016-10-17 06:50
Hi @infectormp, this issue has been fixed in release v1.2.0. Feel free to reopen this ticket if the problem persists on your end.

**Closed by stripthis** 2016-10-17 06:50 UTC
Labels: bug

**Comment by kumaip** [comment] 2017-06-14 16:32
Hi, I still get this error message for one of my users. 
I installed the last version of Passbolt.
Thx for your response
![passbolt](https://user-images.githubusercontent.com/25325788/27143776-c1fa5caa-512f-11e7-8178-453efb19e085.png)

**Comment by stripthis** [comment] 2017-06-14 17:16
hi @kumaip, are you sure this is the same error? Can you show us what is in the console? That might be an issue with the key of that user and not the http headers format. If that's not the case (e.g. if it's not the same cause) it's best if you open a new issue.

**Comment by kumaip** [comment] 2017-06-15 07:44
@stripthis 
hi, how can I show you what is in the console?

**Comment by stripthis** [comment] 2017-06-15 09:07
You can open the Firefox Browser Console in one of two ways:
- from the menu: select "Browser Console" from the Web Developer submenu in the Firefox Menu
- from the keyboard: press Ctrl+Shift+J

**Comment by kumaip** [comment] 2017-06-15 10:04
ok; the use sent me this
![passbolt2](https://user-images.githubusercontent.com/25325788/27176427-c15237a8-51c2-11e7-9faf-744ea3cf56e4.png)

**Comment by stripthis** [comment] 2017-06-15 10:17
Alright it's not the same issue, so I moved it #92.
Can you provide us with more information there?
