### ISSUE TITLE
Fatal error: Class 'Status' not found

### ISSUE THREAD

**Issue by detnon** [passbolt/passbolt#21] opened 2016-09-21 12:59 UTC
Hi guys and girls,

So after configuring everything else, i get this error in the browser when connecting to `https://passbolt.DOMAIN.com`

`
Fatal error: Class 'Status' not found in /home/passbolt/passbolt/app/Controller/CakeErrorController.php on line 63`

Any Idea what could be causing this?

**Running on:** 

- Debian 8.6
- Apache 2.4
- PHP 5.6

**Comment by stripthis** [comment] 2016-09-21 14:14
Hi there,

That's the first time we're seing this one. It's strange that CakeErrorController can not find the Status class, since this class is included in the boostrap.php which is run for every request. So we're going to need a little bit more information to squash that one i'm afraid. Here is a few questions to see if we can get more info to identify the problem:
- Are you using the latest version of passbolt?
- What information do you get on https://passbolt.DOMAIN.com/healthcheck
- Can you check that boostrap.php is present in app/Config?
- Can you also check if the file Status.php file is present in app/Lib?
- Could you have changed any of these two files by mistake maybe? 
- Can you check if there is anything interesting in the php logs?

Worst comes to worst I'll try to do a fresh install on a new Debian 8.6 tomorrow see if I can reproduce the issue, since 8.6 was released on the 17th of September maybe that is a new regression.

Thanks for trying out passbolt and sorry for the bumpy ride. Hopefully we can work that one out together!

**Comment by detnon** [comment] 2016-09-21 14:28
Hey, Thanks for getting back to me so quickly,

**To answer you questions:**
- Yes, the build is up to date
- The same error
- Bootstrap.php is present
- Status.php is present
- No, but anything is possible at this point I think!



And no problem, Im happy to work it out with you!

Looking to use this is my workplace,  Looking forward to the chrome extension being developed :)

**Comment by stripthis** [comment] 2016-09-23 13:07
Hi @detnon,

I did a fresh install of passbolt on a brand new Debian 8.6 but unfortunately I could not reproduce the problem. Can you try double checking the permissions on the file system? Let me know if you have more information we could use to help get started.

Cheers,

**Comment by stripthis** [comment] 2016-09-23 13:30
Hi @detnon I think I could reproduce the issue. It occurs when you app.php is not present. Can you confirm that you have created app/Config/app.php from app.php.default?

**Comment by detnon** [comment] 2016-09-23 13:48
Hey Remy, thanks for taking a look. I can confirm that`app.php` exists in `/home/<USER>/passbolt/app/Config/`

and have configured it with my GPG information.

**Comment by detnon** [comment] 2016-09-23 14:07
Just to add, would there be any issue in having passbolt run in any location other than `/var/www/` ?

Will test this now..

**Comment by stripthis** [comment] 2016-09-24 13:23
Ok, can you show me the permission for that file? I suspect apache can not reach it. Since its running in a /home/<user> you need to make sure apache can reach it, like by adding www-data to your user group for example.

**Comment by stripthis** [comment] 2016-10-14 11:48
@detnon did you manage to make it run? Is it ok if I close this issue?

**Comment by detnon** [comment] 2016-10-14 11:52
sorry remy yes!

all is well, just waiting for further releases now :)

**Comment by stripthis** [comment] 2016-10-14 12:48
Great we have one coming your way in a few hours :)

**Closed by stripthis** 2016-10-14 12:48 UTC
Labels: bug

**Comment by thberger** [comment] 2018-03-01 15:03
Hello, I have the exactly same issue with v. 1.6.9. 
I run CentOS 7, all above mentioned files are present (app.php etc.) and have the correct permissions set.

Can you help me get passbolt running?

**Comment by detnon** [comment] 2018-03-01 15:29
Hey man,

Unfortunately im working somewhere completely different that doesnt use passbolt anymore, so i wont be able to take a look at my configs :( 

Ill check sone other posts i made online to see if there were any answers

(Fyi - i did eventually get it working! )

Good luck! 

SD

⁣Sent from BlueMail ​
